### PR TITLE
[feat]: Adding maps

### PR DESCRIPTION
**Pull request by Alystrasz**
Importing Google Maps API to display maps for Android and iOS (the latter needing to be tested).

We need to find a way to manage API keys, for they must not appear publicly on the repository; those currently used are from my own Google account.

### CODE REVIEW

**Comment by rouvoy** [comment]
There is a way to inject them from the CI with encrypted keys. We use to do that for previous apps, like Apolline-android.

**Comment by Alystrasz** [comment]
@m3ftah could you try to run it again? I explicitely disabled map controls in my latest commit.

**Comment by m3ftah** [comment]
I have tried it and it is working.

**Comment by rouvoy** [comment]
LGTM

**Pull request merged**
