### PR TITLE
[feat] search + save places

### LINKED ISSUE #15: Adding screen for favorite places
Include a new screen to deal with the popularity of favorite places.

### LINKED ISSUE #19: Fixing linter errors
- **Dead code**: `lib/utils/charts/gaugeChart.dart:61:5`
- **Unused import**: `'package:intl/intl.dart' • lib/utils/charts/lineChart.dart:5:8`

### PR DESCRIPTION
**Pull request by Alystrasz**
This PR adds place-related features:
* search bar, to find a place from its name;
* card displaying place details;
* a place can now be saved on local database.

--- 

Here's a preview of these features:

### CODE REVIEW

**Comment by m3ftah** [comment]
hello, this is how it looks in iOS, I need the Google Places API key to be able to search places.

Apr-30-2020 21-53-47

**Comment by m3ftah** [comment]
When I search for a place, I get this exception : 
Apr-30-2020 23-53-25

`flutter: hitting https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=euro%20tech&inputtype=textquery&fields=name,place_id,formatted_address,geometry&key=*****************************
flutter: going to LatLng(50.70076950000001, 3.0851495)
flutter: {formatted_address: 37 Rue César Loridan, 59910 Bondues, France, geometry: {location: {lat: 50.70076950000001, lng: 3.0851495}, viewport: {northeast: {lat: 50.70203502989273, lng: 3.086527729892723}, southwest: {lat: 50.69933537010728, lng: 3.083828070107278}}}, name: Financiere Euro-tech, place_id: ChIJ2Xe8sdfdsfdsfdsfRhMvHc8jHwvs}
flutter: Favorite{name: Financiere Euro-tech, address: 37 Rue César Loridan, 59910 Bondues, France}
flutter: adding new place (ChIJ2XdsfdsfdsfsHc8jHwvs)
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=20 "datatype mismatch" UserInfo={NSLocalizedDescription=datatype mismatch}) sql 'INSERT OR REPLACE INTO favorites (id, name, address) VALUES (?, ?, ?)' args [ChIJ2Xe8K8ArfdsfdsHc8jHwvs, Financiere Euro-tech, 37 Rue César Loridan, 59910 Bondues, France]}
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:12:7)
<asynchronous suspension>
#1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:30:7)
#2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
#3      SqfliteDatabaseMixin.txnRawInsert.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:383:14)
#4      SqfliteDatabaseMixin.txnSynchronized.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:327:22)
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
<asynchronous suspension>
#6   <…>`

**Comment by m3ftah** [comment]
I just had to reinstall the app to make it work.
LGTM.

**Review by m3ftah — APPROVED** [review]
LGTM

**Comment by rouvoy** [comment]
closes #7

**Pull request merged**
