### PR TITLE
[feat] Adding the support for CI

### PR DESCRIPTION
**Pull request by m3ftah**
Added linter, Android APK build and iOS package build.

### CODE REVIEW

**Comment by rouvoy** [comment]
Can you add the PWA build as well?

**Comment by rouvoy** [comment]
Any chance to put the binaries somewhere?

**Comment by rouvoy** [comment]
closes #4

**Comment by Alystrasz** [comment]
When is the CI triggered? When a PR is merged into master?

**Comment by m3ftah** [comment]
Yes, also whenever you do a push in any branch.

**Comment by m3ftah** [comment]
> Can you add the PWA build as well?

There will be a lot of files added, I think that may be the case for a new PR. Meanwhile, this will unblock other PRs waiting for their builds to be validated.

**Review by Alystrasz — APPROVED** [review]
Cool !
LGTM

**Pull request merged**
